"""E3.4: reproducibility hardening — the floating-point story, proven (NFR-2).

The contract: **exact on the same platform + pinned versions; within-tolerance across
platforms or version drift — with the drift named; symbolic results exact everywhere;
and a non-exact rerun with NO drift is a bug, said out loud.**

The committed reference artifacts (``tests/reference_artifacts/``, generated by
``scripts/make_reference_artifacts.py`` on Linux) are the cross-platform transfer
proof: CI reruns every one on Linux, macOS, and Windows. ``failed`` is never
acceptable; on a matching environment the verdict must be ``exact``. Regenerate the
references only deliberately — a red here is a finding, never noise to silence.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from assay.artifact import capture_environment, load_artifact, rerun

_REFERENCES = sorted(
    (Path(__file__).parent / "reference_artifacts").glob("*.result.json")
)


def test_the_reference_set_is_present_and_spans_the_method_kinds() -> None:
    assert len(_REFERENCES) == 10
    kinds = {load_artifact(path).template.method.kind for path in _REFERENCES}
    assert kinds == {"formula", "symbolic", "solver"}


@pytest.mark.parametrize("path", _REFERENCES, ids=[p.stem for p in _REFERENCES])
def test_reference_artifact_reruns(path: Path) -> None:
    """The NFR-2 verdict ladder, per artifact, on every CI platform."""
    artifact = load_artifact(path)
    reproduction = rerun(artifact)
    assert reproduction.status != "failed", reproduction.detail
    same_environment = artifact.environment == capture_environment()
    if same_environment:
        # exact same-platform is the promise, not an aspiration
        assert reproduction.status == "exact", reproduction.detail
    elif reproduction.status == "within-tolerance":
        # a non-exact verdict must carry its diagnosis
        assert "environment drift" in reproduction.detail, reproduction.detail


def test_symbolic_references_are_exact_everywhere() -> None:
    """Symbolic results have no floating-point story: exact on every platform,
    every version, by construction."""
    for path in _REFERENCES:
        artifact = load_artifact(path)
        if artifact.template.method.kind != "symbolic":
            continue
        assert rerun(artifact).status == "exact", path.stem


def test_artifact_bytes_are_hash_seed_independent(tmp_path: Path) -> None:
    """PYTHONHASHSEED must not leak into artifacts (NFR-1): two subprocesses with
    different seeds write byte-identical files."""
    script = (
        "import sys; from assay.artifact import create_artifact, save_artifact; "
        "from assay.ir import IR; from assay.templates import golden_templates; "
        "catalog = {t.id: t for t in golden_templates()}; "
        "ir = IR.model_validate({'domain': 'algebra', 'task': 'solve_equation.univariate', "
        "'setup': {'expression': 'x**2 - 5*x + 6 = 0'}}); "
        "save_artifact(create_artifact(ir, catalog[ir.task]), sys.argv[1])"
    )
    outputs = []
    for seed in ("0", "424242"):
        out = tmp_path / f"seed-{seed}.result.json"
        subprocess.run(
            [sys.executable, "-c", script, str(out)],
            check=True,
            env={**os.environ, "PYTHONHASHSEED": seed},
        )
        outputs.append(out.read_bytes())
    assert outputs[0] == outputs[1]


def test_recreating_a_reference_is_byte_identical_here(tmp_path: Path) -> None:
    """In-process determinism sweep: rebuilding a reference artifact from its own IR
    reproduces the committed bytes exactly when the environment matches."""
    from assay.artifact import create_artifact, save_artifact

    for path in _REFERENCES:
        artifact = load_artifact(path)
        if artifact.environment != capture_environment():
            pytest.skip("reference environment differs — the rerun test covers this")
        rebuilt = create_artifact(artifact.ir, artifact.template)
        out = save_artifact(rebuilt, tmp_path / path.name)
        assert out.read_bytes() == path.read_bytes(), path.stem


def test_reruns_are_stable_under_repetition() -> None:
    """Rerunning twice gives the same verdict and the same recomputed values —
    reproduction itself is deterministic."""
    artifact = load_artifact(_REFERENCES[0])
    first, second = rerun(artifact), rerun(artifact)
    assert first.status == second.status
    assert first.answer.result == second.answer.result


def _keys(node: object) -> set[str]:
    if isinstance(node, dict):
        found = set(node)
        for value in node.values():
            found |= _keys(value)
        return found
    if isinstance(node, list):
        found = set()
        for value in node:
            found |= _keys(value)
        return found
    return set()


def test_references_are_timestamp_free() -> None:
    """No wall-clock anywhere in an artifact (NFR-1/NFR-2): byte-stable forever."""
    for path in _REFERENCES:
        keys = {key.lower() for key in _keys(json.loads(path.read_text(encoding="utf-8")))}
        assert not keys & {"timestamp", "created", "created_at", "date", "time"}, path.stem